language: cpp
os:
- linux
- osx
compiler:
- gcc
matrix:
  allow_failures:
  - os: osx
before_install:
- sudo apt-get install cmake
- sudo apt-get install mercurial
- sudo apt-get install git
- sudo apt-get install subversion
- git config --global user.email "travis-ci@example.com"
- git config --global user.name "Build Server"
install: 
- wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
- bii setup:cpp
script:
- bii init
- bii open manu343726/oo-cmake
- echo "" > blocks/manu343726/oo-cmake/CMakeLists.txt #Empty CMakeLists.txt to override default biicode one
- rsync -av --exclude="blocks" --exclude="bii" --exclude=".git" --exclude=".gitignore" . blocks/manu343726/oo-cmake
- cmake -P build/script.cmake
after_success: cmake -P build/after_success.cmake
after_failure: cmake -P build/after_failure.cmake
after_script: cmake -P build/after_script.cmake
deploy:
  provider: biicode
  user: manu343726
  password:
    secure: ZBdHcI8HEKMSBZbx5xWT5d7iIzm6db8YDibt7TNC9xM3B30+/D+oFXkvMquxp2cYuhhU2cX+IAwLA4AhJmbYzDvUHnIA+7fJjO8DFngf933cv7lO+Wu/pbEN9gmn/nNxR9zZ1kQfH627gWaehq0MQEhXyLebTzDjY3u1h55PIpU=
  skip_cleanup: true #The biicode block is generated during build, don't discard build changes!
