language: cpp
os:
- linux
- osx
compiler:
- gcc
matrix:
  allow_failures:
  - os: osx
notifications:
  slack: fallto:MlnVOMNkx8YopsaSSxqh2Rcr
before_install:
- sudo apt-get install cmake
- sudo apt-get install mercurial
- sudo apt-get install git
- sudo apt-get install subversion
- git config --global user.email "travis-ci@example.com"
- git config --global user.name "Build Server"
install: 
script: cmake -P build/script.cmake
after_success: cmake -P build/after_success.cmake
after_failure: cmake -P build/after_failure.cmake
after_script: cmake -P build/after_script.cmake
deploy:
  provider: biicode
  user: Manu343726
  password:
    secure: ZBdHcI8HEKMSBZbx5xWT5d7iIzm6db8YDibt7TNC9xM3B30+/D+oFXkvMquxp2cYuhhU2cX+IAwLA4AhJmbYzDvUHnIA+7fJjO8DFngf933cv7lO+Wu/pbEN9gmn/nNxR9zZ1kQfH627gWaehq0MQEhXyLebTzDjY3u1h55PIpU=
